// --== CS400 File Header Information ==--
// Name: Fangjun Zhou
// Email: fzhou48@wisc.edu
// Team: CG blue
// TA: Xi
// Lecturer: Gary Dahl
// Notes to Grader: <optional extra notes>

/**
 * The interface that provide data for the backend developer
 *
 * @author fangjunzhou
 * @version 1.0
 */
public interface MapReaderInterface<T> {

  /**
   * Get the map generated by data wrangler
   *
   * @return a Map object implements GraphADT
   */
  public GraphADT<T> getMap();

  /**
   * An overload of getMap function, can specify the size of the map
   *
   * @param width the width of the map
   * @param height the height of the map
   * @return the generated map
   */
  public GraphADT<T> getMap(int width, int height);

  /**
   * Get the width of the whole map
   *
   * @return the width of the map
   */
  public int getMapSizeX();

  /**
   * Get the height of the whole map
   *
   * @return the height of the whole map
   */
  public int getMapSizeY();

  /**
   * Get all the map names that frontend and backend can use
   *
   * @return all the map names
   */
  public static String[] getMapNames(){
    String[] mapNames = {"emptyMap", "testMap"};
    return mapNames;
  }
}
